#!/usr/bin/env sh

set -e
set -u

test -n "$GH_TOKEN"
git diff --quiet && echo "No updates." && exit 0

CREATE_PR_URL="https://api.github.com/repos/zonedb/zonedb/pulls"
DATE="$(date -u +%Y-%m-%d-%H-%M-%S)"
BRANCH="data-${DATE}"
CHANGED_ZONES="$(git status --short | grep metadata | cut -f 2 -d / | sed '/.json/s///' | tr '\n' ' ')"

git checkout -q -b $BRANCH
git add zones.txt metadata/*.json zones.go
git commit --author="zonedb bot <bot@zonedb.org>" -m "Automated data update: $DATE"
git push origin $BRANCH
git co master

PR=$(cat <<EOF
{
  "title": "Automated data update $DATE",
  "body": "$CHANGED_ZONES",
  "head": "$BRANCH",
  "base": "master"
}
EOF)

JSON="${TMPDIR}pull-request.json"

curl -sS -i \
--header "Authorization: token ${GH_TOKEN}" \
--data "${PR}" \
--request POST ${CREATE_PR_URL} > $JSON

grep -q "201 Created" $JSON || (cat $JSON && exit 1)
echo Created "$(grep -A1 '"self": {' $JSON | grep href | cut -f 2- -d ':')"
	# "_links": {
    #   "self": {
    #     "href": "..."
    #   },
